### ISSUE TITLE
RFC Naming: Extensions

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/flask-appfactory#15]
The name "extensions" as used in Flask-AppFactory causes some confusion with Flask Extensions hence the name might not be the most appropriate.

**Concepts:**
- Flask extensions: As defined on http://flask.pocoo.org/docs/0.10/extensiondev/ and examples on http://flask.pocoo.org/extensions/.
  
  Here a very simplified example of a factory function where Flask extensions are being initialised:

``` python
def create_app():
    app = Flask("myapp")
    db = FlaskSQLAlchemy(app)
    cache = FlaskCache(app)
    return app
```
- Flask-AppFactory extensions: Actually the core of Flask-AppFactory extensions is that they are used to initialise your Flask application - i.e. your monolithic application factory function is split into parts which each can be easily enabled or disabled:

``` python
def create_app():
    class config:
        EXTENSIONS = ["sqlachemy","cache"]
    return appfactory("myapp", config)

#sqlalchemy.py
def setup_app(app):
    db = FlaskSQLAlchemy(app)

#cache.py
def setup_app(app):
    cache = FlaskCache(app)
```

To complicate things, it is actually possible to not have a `setup_app` method, if you Flask-Extension just takes an `app` argument`` (see [example](https://github.com/mattupstate/flask-mail/blob/master/flask_mail.py#L551)):

``` python
def create_app():
    class config:
        EXTENSIONS = ["flask_sqlalchemy:FlaskSQLAlchemy", "flask_cache:FlaskCache"]
    return appfactory("myapp", config)
```

I.e. the main purpose of Flask-AppFactory extensions is to initialise a Flask Application.

**Proposals:**

1) Live with the ambiguity and call it AppFactory extensions.
2) or, rename Extensions to something along the lines of:
- initializers
- initialization
- appsetup
- setupsteps
- ?

@jirikuncar @jbenito3 @tiborsimko @nharraud ?

**Comment by jbenito3** [comment]
As an Invenio newbie that knew the concept of Flask Extension, I've got quite confused at the very beginning with the name. Thanks to @lnielsen's explanations I've got to understand that actually those were not flask-like extensions but kind-of initialisers. If this is the case, I think another naming would help the project new-comers. 

I guess those Invenio-extensions are used to setup flask-only modules/extensions, am I right? If so, another names could be: 
- extsetup 
- extini

**Comment by tiborsimko** [comment]
Some quick notes in between two AAHEP8 talks:

(1) The naming ambiguity could be lessened by a consistent prefix-oriented naming such as:

```
Flask-AppFactory
Flask-AppFactory-Ext-Foo
Flask-AppFactory-Ext-Bar
```

This would express well that the package in question is an "extension" to Flask-AppFactory, not to Flask itself. (At the price of an extra length, but I'd take clarity over shortness anytime, since the auto completion helps etc.)

(2) One could perhaps leave out Ext and have:

```
Flask-AppFactory
Flask-AppFactory-Foo
Flask-AppFactory-Bar
```

which would seem a good compromise between clarity and length.

(3) As for another name for the "extension" concept, let's aim at inventing a one-word concept (such as "initaliser", "loader", "enabler") rather than a multi-word concept (such as mentioned "appsetup", "setupstep", "extini").

**Comment by jirikuncar** [comment]
I like `Flask-AppSetup`.

**Comment by tiborsimko** [comment]
From a several-years-ahead perspective, there may be several independent initalisers for several
independent things, each living in its own Python package. Hence I was looking at a consistent naming schema that can accommodate more than one "extension" package?!

**Comment by jirikuncar** [comment]
We are planning to deprecate this package or pass the package to a new maintainer.
